### PR TITLE
fix: normalize ALL_CAPS hymn titles to title case for Icibemba and similar hymnals

### LINKED ISSUE #175: Fix hymn titles in some hymn that have titles in uppercase
This was noted in this PR #174 and it is happening mostly for the bemba version

### PR DESCRIPTION
**Pull request by wiliyam**
## Summary
Fixes #175

Some hymnal files (notably Icibemba) store hymn titles in ALL CAPS. This caused them to display inconsistently compared to other hymnals.

## Changes
- Added `src/utils/formatHymnTitle.ts` — detects ALL_CAPS titles and converts to Title Case
- Applied in `HymnListItem.tsx` and `HymnContent.tsx` where titles are rendered
- Mixed-case titles from other hymnals are returned unchanged

## Testing
- Icibemba hymn titles now display in Title Case
- All other hymnal titles are unaffected (non-ALLCAPS strings pass through unchanged)

### CODE REVIEW

**Comment by OlivierJM** [comment]
@wiliyam Thanks for your contribution. 

I tested this branch and it seems we still have some hymns that are still in uppercase

Screenshot 2026-04-02 at 8 21 56 AM
Screenshot 2026-04-02 at 8 21 43 AM
Screenshot 2026-04-02 at 8 21 25 AM

File: src/utils/formatHymnTitle.ts [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+ * detects that case and converts to title case so all hymnals render
+ * consistently. Mixed-case titles are returned unchanged.
+ *
+ * See: https://github.com/Faith-UnFeigned/cis-web/issues/175
+ */
+export function formatHymnTitle(title: string): string {
+  if (!title) return title;
+  // Consider a title "all caps" if it has no lowercase letters but has at least one uppercase letter
+  const isAllCaps = title === title.toUpperCase() && /[A-Z]/.test(title);
+  if (!isAllCaps) return title;
```
Comment (OlivierJM) [inline src/utils/formatHymnTitle.ts]: We shouldn't have to check this at all, we can just turn the title into a SentenceCase despite its original format.

**Review by OlivierJM — CHANGES_REQUESTED** [review]

**Comment by wiliyam** [comment]
Thanks for testing @OlivierJM! You're right — the previous fix only caught 100% uppercase titles, but some hymnals have titles where most (but not all) letters are uppercase. Updated the logic to normalize any title where **70%+ of letters are uppercase**, which catches both fully-caps and mostly-caps patterns. Please test again and let me know!

**Comment by OlivierJM** [comment]
Thanks, It looks okay now but I think the implementation is unnecessarily complex but this works.

**Review by OlivierJM — APPROVED** [review]

**Comment by wiliyam** [comment]
Thank you for merging! Happy to contribute more if needed 🙏
